Added Record toEntries, fromEntries
gcanti/fp-ts pull request #1552
Opened 2021-07-31 22:53 UTC by bravely

* Added `Record.toEntries` and `Record.fromEntries`, to facilitate a common need of folks coming over from 'normal' JS.

2021-08-02 07:39 UTC, mlegenhausen commented
`toEntries` is `toReadonlyArray` https://github.com/gcanti/fp-ts/blob/master/src/ReadonlyRecord.ts#L136-L138

`fromEntries` is `fromFoldable`

```ts
import * as RR from 'fp-ts/ReadonlyRecord'
import * as RA from 'fp-ts/ReadonlyArray'
import * as S from 'fp-ts/Semigroup'

RR.fromFoldable(S.last<string>(), RA.Foldable)([['a', 'b'], ['c', 'd'], ['a', 'e']])
// { a: 'e', c: 'd' }
```

2021-08-02 15:15 UTC, bravely commented
@mlegenhausen Didn't realize `toEntries` was `toArray`/`toReadonlyArray`, that works.

The other though, I feel like there should be a convenience for, especially considering we could easily auto-type it.

2021-08-03 07:54 UTC, mlegenhausen commented
@bravely sorry overlooked that you just defined an alias for `fromFoldable`.

If you could adjust your PR so the `toEntries` and `fromEntries` are defined in `ReadonlyRecord` and just reexported in `Record` the last decision lies by @gcanti.

IMHO it would be a good addition especially for people who are new `fp-ts` programmers and for me  `RR.fromFoldable(S.last<A>(), RA.Foldable)` is the most used configuration.

2021-08-03 16:08 UTC, bravely commented
@mlegenhausen I appreciate the support! I matched the feature in `ReadonlyRecord`, however I couldn't simply alias the result because of the nature of the `readonly` parameters. So I made them effectively match, with `ReadonlyRecord` creating a `ReadonlyArray` and `Record` creating an `Array`.

2021-09-06 15:25 UTC, mlegenhausen commented
Looks good for me could you please add `@since 2.12.0` to your comments?

2021-09-26 16:59 UTC, bravely commented
@mlegenhausen Apologies for how long it took, but I've added those now.

2021-09-27 07:04 UTC, mlegenhausen commented
@bravely please check the CI result. In this case you need to run `npm run fix-prettier`.

2021-09-30 00:54 UTC, bravely commented
@mlegenhausen Should be good to go now!

2021-09-30 07:44 UTC, mlegenhausen approved these changes

2021-11-20 21:55 UTC, steida commented
I just realized I need such helpers.  @gcanti Can you please merge it? Thank you.

2021-11-22 10:35 UTC, gcanti requested changes

2021-11-22 10:35 UTC, gcanti commented on src/ReadonlyRecord.ts
> +type Semigroup<A> = Se.Semigroup<A>
@bravely I believe this can be replaced by

```ts
import Semigroup = Se.Semigroup
```

2021-11-22 10:35 UTC, gcanti commented on src/Record.ts
> +type Semigroup<A> = Se.Semigroup<A>
idem

2021-12-14 01:26 UTC, bravely commented
@gcanti Updated!

2021-12-14 15:58 UTC, gcanti approved these changes

2021-12-14 15:59 UTC, merged

2021-12-14 16:00 UTC, gcanti commented
Thank you @bravely 👍