Alternative: add getAlternativeMonoid
gcanti/fp-ts pull request #1717
Opened 2022-06-06 16:54 UTC by willheslam

This provides a way to lift a semigroup into a monoid via an alternative...
think of it like a generalised version of `Option`'s `getMonoid`, except it applies to any `Alternative`.

It also means any module without a specialised `getMonoid` function like `TaskOption` and `IOOption` also have a way to produce an amalgamation.

Hopefully this is useful and not a duplication of functionality.
Alternatively, should all Alternative-capable modules expose a `getMonoid` function?

I did debate adding a way to get an Alternative Semigroup from a Semigroup (and Alternative Monoid from a Monoid) but I realised this had the biggest bang for buck in utilising the capabilities of the underlying Alternative.
I am pretty sure the order of `() => F.alt(first, () => second))` is irrelevant given it's a Semigroup.

(If the tests are redundant I'd be happy to rewrite them as showing identical behaviour to `Option`'s `getMonoid` function.)

2022-09-07 15:37 UTC, gcanti commented
@willheslam not sure why the CI is failing, the log is no longer available

2022-09-07 15:39 UTC, gcanti requested changes

2022-09-07 15:39 UTC, gcanti commented on src/Alternative.ts
> + * @since 2.12.2
this should become `@since 2.13.0`

2022-09-08 23:00 UTC, willheslam commented on src/Alternative.ts
> + * @since 2.12.2
Fixed!

2022-09-08 23:06 UTC, willheslam commented
> @willheslam not sure why the CI is failing, the log is no longer available

I don't remember either, but it's passing now. Thanks for reviewing this!

2022-09-09 04:50 UTC, gcanti approved these changes

2022-09-09 04:51 UTC, merged

2022-09-09 04:53 UTC, gcanti commented
Thank you @willheslam

2023-09-12 18:35 UTC, CarstenLeue commented
Hi @willheslam, not sure if you see this on a merged PR but I have the following question:

in the implementation

```ts
return {
      concat: (first: HKT<F, A>, second: HKT<F, A>) =>
        F.alt(SF.concat(first, second), () => F.alt(first, () => second)),
      empty: F.zero()
    }
```

both `first` and `second` are being used twice and might also be evaluated twice, e.g. if `SF.concat(first, second)` fails and the alternative gets pulled in, `first` will be evaluated again.
If this is an effectful operation, e.g. a `TaskEither` this task would be triggered twice. This might be a performance concern but also might lead to unexpected results for side effects.

Is there a particular conceptual reason to evaluate the parameters twice? Do you see any potential issue with this?