Applicative4 added to Record traverse
gcanti/fp-ts pull request #1733
Opened 2022-07-18 12:40 UTC by mlegenhausen

This allows the usage for `Record#traverse` with `StateReaderTaskEither` or `hyper-ts/ReaderMiddleware`.

2022-07-19 14:05 UTC, gcanti requested changes

2022-07-19 14:05 UTC, gcanti commented on src/ReadonlyRecord.ts
> +): <K extends string, S, R, E, A, B>(
here `K extends string` is a typo IMO

2022-07-19 14:05 UTC, gcanti commented on src/Record.ts
> +): <K extends string, S, R, E, A, B>(
idem

2022-07-22 20:31 UTC, mlegenhausen commented on src/ReadonlyRecord.ts
> +): <K extends string, S, R, E, A, B>(
Copy and paste error.

2022-07-25 08:05 UTC, gcanti approved these changes

2022-07-25 08:05 UTC, merged