Add tap for Identity
gcanti/fp-ts pull request #1943
Opened 2024-06-25 06:35 UTC by forno

Close #1942

2024-06-27 13:18 UTC, gcanti requested changes

2024-06-27 13:18 UTC, gcanti commented on src/Identity.ts
> + * @since 2.17.0
```suggestion
 * @since 2.16.7
```

2024-06-27 13:18 UTC, gcanti commented on src/Identity.ts
>  export const chainFirst: <A, B>(f: (a: A) => B) => (first: A) => A = /*#__PURE__*/ chainFirst_(Chain)
```suggestion
export const chainFirst: <A, B>(f: (a: A) => B) => (first: A) => A = tap
```

2024-06-29 15:26 UTC, gcanti requested changes

2024-06-29 15:26 UTC, gcanti commented on src/Identity.ts
> + * @since 2.16.0
```suggestion
 * @since 2.16.7
```

2024-06-29 15:28 UTC, forno commented on src/Identity.ts
> + * @since 2.16.0
Oh. sorry. I will fix soon.

2024-06-29 15:43 UTC, gcanti approved these changes

2024-06-29 15:47 UTC, merged